# Originally from Nxrocks https://github.com/tinesoft/nxrocks/blob/develop/.github/actions/install-dependencies/action.yml
name: 'Install dependencies'
description: Install node and pnpm, then run pnpm install

inputs:
  node-version: # id of input
    description: 'Node version'
    required: false
    default: 18

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8.2

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v3
      with:
        lookup-only: true
        path: '**/node_modules'
        key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Install packages
      run: pnpm install --frozen-lockfile
      shell: bash
