name: Nx Windows CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]
    env:
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: git fetch --no-tags --prune --depth=5 origin main
        shell: powershell
      - run: yarn install --prefer-offline --frozen-lockfile --non-interactive
        shell: powershell
      - run: yarn affected:build --base=origin/main --head=HEAD
        shell: powershell
      - run: yarn affected:lint --base=origin/main --head=HEAD --parallel
        shell: powershell
      - run: yarn affected:test --base=origin/main --head=HEAD --parallel
        shell: powershell
      - run: yarn affected:e2e --base=origin/main --head=HEAD
        shell: powershell
