name: nxext macos CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  setup:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
        - uses: mansagroup/nrwl-nx-action@v1
        with:
          targets: build,lint,test
          affected: 'true' # Defaults to true, therefore optional
