name: nxext windows CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  setup:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Get origin main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
      - uses: actions/cache@v1
        id: workspace-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-workspace-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-workspace-
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
  lint:
    runs-on: windows-latest

    needs: [setup]
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Get origin main
        if: github.event_name == 'pull_request'
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
      - uses: actions/cache@v1
        id: workspace-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-workspace-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-workspace-
      - name: Run On main
        if: github.event_name == 'push'
        run: yarn affected:lint --parallel
        env:
          NX_BRANCH: ${{ github.event.number }}
          NX_RUN_GROUP: ${{ github.run_id }}
      - name: Run on PR
        if: github.event_name == 'pull_request'
        run: yarn affected:lint --base=origin/main --head=HEAD --parallel
        env:
          NX_BRANCH: ${{ github.event.number }}
          NX_RUN_GROUP: ${{ github.run_id }}

  test:
    runs-on: windows-latest

    needs: [setup]

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Get origin main
        if: github.event_name == 'pull_request'
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
      - uses: actions/cache@v1
        id: workspace-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-workspace-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-workspace-
      - name: Run On main
        if: github.event_name == 'push'
        run: yarn affected:test --parallel
        env:
          NX_BRANCH: ${{ github.event.number }}
          NX_RUN_GROUP: ${{ github.run_id }}
      - name: Run on PR
        if: github.event_name == 'pull_request'
        run: yarn affected:test --base=origin/main --head=HEAD --parallel
        env:
          NX_BRANCH: ${{ github.event.number }}
          NX_RUN_GROUP: ${{ github.run_id }}

  e2e:
    runs-on: windows-latest

    needs: [setup]

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Get origin main
        if: github.event_name == 'pull_request'
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
      - uses: actions/cache@v1
        id: workspace-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-workspace-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-workspace-
      - name: Run On main
        if: github.event_name == 'push'
        run: yarn affected:e2e --base=origin/main --head=HEAD
        env:
          NX_BRANCH: ${{ github.event.number }}
          NX_RUN_GROUP: ${{ github.run_id }}
      - name: Run on PR
        if: github.event_name == 'pull_request'
        run: yarn affected:e2e --base=origin/main --head=HEAD
        env:
          NX_BRANCH: ${{ github.event.number }}
          NX_RUN_GROUP: ${{ github.run_id }}
