name: nxext macos CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  setup:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Get origin main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run build actions
        uses: mansagroup/nrwl-nx-action@v1
          with:
            targets: lint-test,build
