name: Nx Windows CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    env:
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
      NX_BRANCH: ${{ github.event.number }}
      NX_RUN_GROUP: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch --no-tags --prune --depth=5 origin main
      - run: yarn install --frozen-lockfile
      - run: yarn affected:build --base=origin/main --head=HEAD --with-deps
      - run: yarn affected:lint --base=origin/main --head=HEAD --parallel
      - run: yarn affected:test --base=origin/main --head=HEAD --parallel
      - run: yarn affected:e2e --base=origin/main --head=HEAD
