name: Release

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  release:
    name: Build, Release & Publish
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Checkout the release branch
        run: |
          git fetch --depth=1
          git checkout $GITHUB_REF_NAME

      - name: Install node, pnpm, and dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build, Release on GitHub & Publish to NPM
        env:
          HUSKY: '0' # By default do not run HUSKY install
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm run release --verbose
